version: '3.8'

services:

  website:
    restart: unless-stopped
    image: ghcr.io/alecks20/alecks.dev:latest
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./db:/data/db
    env_file:
      - .env

  proxy:
    image: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup